config/routes.rb
Sra::Application.routes.draw do

	get "search", to: "Search#search"
	
	post '/households', controller: :households, action: :index, as: :households
	
	root to: 'static#landing'
	
	get '/sessions/new', as: :new_user_session
	
	post '/sessions/create', controller: :sessions, action: :create, as: :login

	resources :events

	get "dashboard", to: "dashboard#show", as: :dashboard

	scope "/admin" do
		resources :users
		resources :roles
		resources :areas
		resources :regions

		post '/users/:user_id/roles/:role_id', to: 'UserRole#create', as: :new_user_role
		delete '/users/:user_id/roles/:role_id', to: 'UserRole#destroy', as: :destroy_user_role

        post '/areas/:area_id/users/:user_id/:relationship', to: 'AreasUsers#create', as: :new_area_user
		delete '/areas/:area_id/users/:user_id', to: 'AreasUsers#destroy', as: :destroy_area_user

		post '/areas/:area_id/regions/:region_id', to: 'AreasRegions#create', as: :new_area_region
		delete '/areas/:area_id/regions/:region_id', to: 'AreasRegions#destroy', as: :destroy_area_region
	end

    
    

	resources :households do 
		resources :interviews, shallow: true
		resources :people, shallow: true do
			resources :jobs, shallow: true
		end
        
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
	def show
        @households = Household.all
		@user = User.find(params[:id])
    	respond_to do |format|
      		format.html # index.html.erb
      		format.json { render json: @areas }
        end
		if @user.has_role? "admin"
            admin
        elsif @user.has_role? "manager"
            field_worker
        elsif @user.has_role? "field worker"
            field_worker
		else
            redirect_to households_path
        end
	end

	def field_worker
        @households = @user.households
        #@field_workers = @user.area_relationships.select{|r| r.relationship == "Manager"}.map{|r| r.area}.map{|area| area.area_relationships.select{|r|r.relationship == "Field Worker"}.map{|r| r.user}}.flatten
        #@areas = Area.joins(:users).where(area_relationships:{relationship: "Manager"},users:{id: @user.id})
       # request = RestClient.get "https://sra-api.herokuapp.com/user/#{params[:id]}/households" 
        #@households = JSON.parse(request)
        render :worker
	end
    
    def admin
		@user = User.new
		@users = Users.all
        render :admin
    end
    
    
end

app/helpers/dashboard_helper.rb
module DashboardHelper
    
end

app/views/dashboard/_admin_users_list.html.haml
.table-responsive.col-md-9
  %table.table.table-hover
    %thead
      %tr
        %th
          User Email
        %th
          Role
    %tbody
      - @users.each do |user|
        %tr
          %td{rowspan: user.email.count + 1}
            = link_to user.name, user, class: ['btn', 'btn-info']
        - household.people.each do |person|
          %tr
            %td
              = link_to person.given_name, person

                

app/views/dashboard/_create_user.html.haml
.container-admin.col-md-3.col-sm-6
  - if notice
    %p.notice
      = notice
  %h2 Create User
  = form_for(@user) do |f|
    .row
      = f.label :email
    .row
      = f.email_field :email, :autofocus => true, class: ['textfield', 'col-xs-12']
    .row
      = f.label :password
    .row
      = f.password_field :password, class: ['textfield', 'col-xs-12']
    .row
      = f.label :password_confirmation
    .row
      = f.password_field :password_confirmation, class: ['textfield', 'col-xs-12']
    .row
      = f.submit "Create User", class: ['btn', 'btn-lg', 'btn-success']

app/views/dashboard/_dashboard_list.html.haml
.table-responsive.col-sm-12.col-md-9.hidden-xs.visible-sm.visible-md.visible-lg
  %table.table.table-hover
    %thead
      %tr
        %th
          Household Name
        %th
          Family Members
        %th
          Interview
          
    %tbody
      - @households.reverse.each do |household|
        %tr
          %td{rowspan: household.people.count + 2}
            = link_to household.name, household
          - household.people.each_with_index do |person, index|
            %tr
              %td
                = link_to person.given_name, person 
              - if index == 0
                %td
                  - interview = household.interview
                  - if interview.nil?
                    = link_to "Interview Family", new_household_interview_path(household), class: [:'button-emphasis']
                  -else
                    = link_to 'View Nutrition', interview, id: "#{interview.id}_show"
          %tr
            %td
              = link_to 'Add Person', new_household_person_path(household), class: [(:'button-emphasis' if household.people.count == 0), (:'button' unless household.people.count == 0)]

.table-responsive.col-xs-12.hidden-sm.hidden-md.hidden-lg
  %table.table.table-hover
    %thead
      %tr
        %th
          Household
        %th
          Next Step
    - @households.each do |household|
      %tbody
        %tr
          %td
            = link_to household.name, household#, class: ['btn', 'btn-primary']
          %td
            - interview = household.interview
            - if household.people.count == 0
              = link_to 'Add Person', new_household_person_path(household), class: [:btn, (:'btn-primary' if household.people.count == 0), (:'btn-info' unless household.people.count == 0)]
            - elsif interview.nil?
              = link_to "Interview Family", new_household_interview_path(household), class: ['btn', 'btn-primary']
            - else
              = link_to 'View Nutrition', interview, id: "#{interview.id}_show"#, class: ['btn', 'btn-primary']

app/views/dashboard/_manager_partial.html.haml
- @areas.each do |area|
  .col-sm-6.col-md-4
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = area.name
      .panel-body.index
        -@field_workers.each do |person|
          %ul
            %li
              = person.email
              %ul
                %li
                  - if person.households.empty?
                    = "No households"
                  - else person.households.name

app/views/dashboard/_meetings_list.html.haml
.col-md-3.col-xs-12
  %table.table
    %thead
      %th
        Household
      %th
        Date
    %tbody
      - @user.events.each do |meeting|
        %tr
          %td

app/views/dashboard/admin.html.haml
%h1 
   Admin Dashboard

.row.btn-toolbar
   = link_to 'Users', users_path, class: [:'toolbar-button'], id: :top
   = link_to 'Roles', roles_path, class: [:'toolbar-button'], id: :top
   = link_to 'Areas', areas_path, class: [:'toolbar-button'], id: :top
  
.container-fluid
   .row-fluid
      .span2
      = render 'dashboard/create_user'

app/views/dashboard/show.html.haml
=@user.roles

app/views/dashboard/worker.html.haml
.container
  .row
    %h1
      Dashboard

  .row
    .toolbar
      = link_to 'New Household', new_household_path, class: [:'toolbar-button']
      = link_to 'New Meeting', new_event_path, class: [:'toolbar-button']
  %br

  .row
    = render 'manager_partial'

  .row
    = render 'dashboard_list'
    = render 'meetings_list'