config/routes.rb
Sra::Application.routes.draw do

	get "search", to: "Search#search"
	
	post '/households', controller: :households, action: :index, as: :households
	
	root to: 'static#landing'
	
	get '/sessions/new', as: :new_user_session
	
	post '/sessions/create', controller: :sessions, action: :create, as: :login

	resources :events

	get "dashboard", to: "dashboard#show", as: :dashboard

	scope "/admin" do
		resources :users
		resources :roles
		resources :areas
		resources :regions

		post '/users/:user_id/roles/:role_id', to: 'UserRole#create', as: :new_user_role
		delete '/users/:user_id/roles/:role_id', to: 'UserRole#destroy', as: :destroy_user_role

        post '/areas/:area_id/users/:user_id/:relationship', to: 'AreasUsers#create', as: :new_area_user
		delete '/areas/:area_id/users/:user_id', to: 'AreasUsers#destroy', as: :destroy_area_user

		post '/areas/:area_id/regions/:region_id', to: 'AreasRegions#create', as: :new_area_region
		delete '/areas/:area_id/regions/:region_id', to: 'AreasRegions#destroy', as: :destroy_area_region
	end

    
    

	resources :households do 
		resources :interviews, shallow: true
		resources :people, shallow: true do
			resources :jobs, shallow: true
		end
        
	end

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id                     :integer          not null, primary key
#  given_name             :string(255)
#  family_name            :string(255)
#  family_relationship_id :integer
#  birthday               :date
#  education_level        :string(255)
#  gender                 :string(255)
#  in_school              :boolean
#  is_alive               :boolean
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  household_id           :integer
#

class Person < SraModel
	json_attributes :id,
		:given_name,
		:family_name,
		:family_relationship_id,
		:birthday,
		:education_level,
		:gender,
		:in_school,
		:is_alive,
		:created_at,
		:updated_at,
		:household_id
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	#before_filter :authenticate_user!
	def new
		@household = Household.find(params[:household_id])
	
		@person = Person.new(family_name: @household.name)
		RestClient.post 'https://sra-api.herokuapp.com/households/persons', {:family_name => @household.name}
		@path = [@household, @person]
		@relationships = FamilyRelationship.all.map do |relationship|
			relationship.name
		end
	end

	def create
		@household = Household.find(params[:household_id])

		#relationship = FamilyRelationship.find_by_name(params[:person][:family_relationship])
		relationship = RestClient.get "https://sra-api.herokuapp.com/households/relationships/#{params[:id]}", {:relationship => params[:person][:family_relationship]}
		@person = Person.new(params[:person].except(:family_relationship)).create
		
		@person.family_relationship = relationship
		@household.people << @person
		RestClient.post 'https://sra-api.herokuapp.com/households/people', {:person => @person}
		respond_to do |format|
			if response.status == 200
				format.html {redirect_to @household}
				format.json {render json: @household, status: :created, location: @household}
			else
				format.html { redirect_to new_household_person_path }
				format.json { render json: @person.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
		@person = Person.find(params[:id])
		@household = @person.household
		@relationships = FamilyRelationship.all.map do |relationship|
			relationship.name
		end
		@path = @person
	end

	def show
		@person = Person.find(params[:id])

	end

	def index
		@household = Household.find(params[:household_id])

		redirect_to @household
	end

	def update
		@person = Person.find(params[:id])
	
		@person.attributes = params[:person].except("family_relationship")
		#relationship = FamilyRelationship.find_by_name(params[:person][:family_relationship])
		relationship = RestClient.get 'https://sra-api.herokuapp.com/households/relationships/:name', {:relationship => params[:person][:family_relationship]}
		@person.family_relationship = relationship
		RestClient.put 'https://sra-api.herokuapp.com/households/people/:id', {:params => {:person => @person}}
		respond_to do |format|
			if response.status == 200 
				format.html {redirect_to @person}
				format.json {render json: @person, status: :created, location: @household}
			else
				format.html { render action: "edit" }
				format.json { render json: @person.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@person = Person.find(params[:id]) 

		@person.delete
		redirect_to household_path(@household)
	end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= form_for(@path) do |form| 
  .row
    = form.label :given_name, class: ["col-sm-4", "col-md-3"]
    = form.text_field :given_name, class: [:textfield, "col-sm-8", "col-md-9"]
  
  .row
    = form.label :family_name, class: ["col-sm-4", "col-md-3"]
    = form.text_field :family_name, class: [:textfield, "col-sm-8", "col-md-9"]

  .row
    = form.label :family_relationship, class: ["col-sm-4", "col-md-3"]
    = form.select :family_relationship, @relationships
  
  .row
    = form.label :birthday, class: ["col-sm-4" , "col-md-3"]
    = form.date_select :birthday, start_year: 1900, end_year: Time.now.year, class: "Hello"
  
  .row
    = form.label :education_level, class: ["col-sm-4" , "col-md-3"]
    = form.select :education_level, ['None', 'Some Elementary', 'Elementary', 'Some Secondary', 'Secondary', 'Some College', 'College']  
  
  .row
    = form.label :gender, class: ["col-sm-4" , "col-md-3"]
    = form.select :gender, ['Male', 'Female', 'Other']  
  
  .row
    = form.label :in_school, class: ["col-sm-4" , "col-md-3"]
    = form.check_box :in_school  
  
  .row
    = form.submit :Submit, class: [:btn, "btn-success", "btn-large", "col-sm-3"]

app/views/people/edit.html.haml
.col-sm-12
  .panel.panel-pimary
    .panel-body
      %h1 
        Edit
        = "#{@person.given_name} #{@person.family_name}"
        %br
      = render 'form'

app/views/people/index.html.haml
= button_to 'New Person', new_household_person_path, class: :button
%ul
  - @people.each do |person| 
    %li
      = link_to "#{person.given_name} #{person.family_name}", household_person_path(@household, person)
      = link_to('Destroy', [@household, person], method: :delete, data: { confirm: 'Are you sure?' })
= button_to('New Person', new_household_person_path(), class: :button)

app/views/people/new.html.haml
.row
  = link_to 'See Family', household_path(@household), class: [:btn, "btn-success", 'col-sm-3', 'col-md-2'], id: :back, method: :get
.col-sm-12
  .panel.panel-pimary
    .panel-body
      %h1 
        New Person
        %br
      = render 'form'

app/views/people/show.html.haml
/.row-fluid
/  .banner
/    %h2
/      Hello world
%h1= @person.given_name + " " + @person.family_name

.row.btn-toolbar
  = link_to 'Edit Person', edit_person_path(@person),  class: [:btn, "btn-large", "btn-success", "col-sm-offset-8", "col-md-offset-10", "col-sm-4", "col-md-2", :right], id: :edit_person_top
  = link_to 'Add Job', new_person_job_path(@person),  class: [:btn, "btn-large", "btn-success", "col-sm-offset-8", "col-md-offset-10", "col-sm-4", "col-md-2", :right]

.col-sm-12
  .panel.panel-primary
    .panel-body
      .row
        %label{class: "col-sm-3"}
          Name:
        %label
          = @person.given_name + " " + @person.family_name
      .row
        %label{class: "col-sm-3"}
          Relationship: 
        %label
          = @person.family_relationship.name
      .row
        %label{class: "col-sm-3"}
          Birthday: 
        %label
          = @person.birthday
      .row
        %label{class: "col-sm-3"}
          Gender: 
        %label
          = @person.gender
      .row
        %label{class: "col-sm-3"}
          In School: 
        %label
          = @person.in_school
      .row
        %label{class: "col-sm-3"}
          Living:
        %label
          = @person.is_alive
%h2
  Jobs

- @person.jobs.each do |job|
  .col-sm-6.col-md-4
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = link_to "#{job.title} #{"(temporary)" if job.seasonal}", job_path(job)
          = link_to 'X', job, method: :delete 
      .panel-body
        = job.description
        = link_to 'Show', job_path(job), class: [:btn, "btn-success", "btn-lg", "col-md-5", "col-sm-5"]
        = link_to 'Edit', edit_job_path(job), class: [:btn, "btn-success", "btn-lg", "col-sm-5", "col-md-5", "col-md-offset-2", "col-sm-offset-2"]

.row.btn-toolbar
  = link_to 'Edit Person', edit_person_path(@person),  class: [:btn, "btn-large", "btn-success", "col-sm-offset-8", "col-md-offset-10", "col-sm-4", "col-md-2", :right], id: :edit_person_bottom
  = link_to 'Add Job', new_person_job_path(@person),  class: [:btn, "btn-large", "btn-success", "col-sm-offset-8", "col-md-offset-10", "col-sm-4", "col-md-2", :right]