config/routes.rb
Sra::Application.routes.draw do

	get "search", to: "Search#search"
	
	post '/households', controller: :households, action: :index, as: :households
	
	root to: 'static#landing'
	
	get '/sessions/new', as: :new_user_session
	
	post '/sessions/create', controller: :sessions, action: :create, as: :login

	resources :events

	get "dashboard", to: "dashboard#show", as: :dashboard

	scope "/admin" do
		resources :users
		resources :roles
		resources :areas
		resources :regions

		post '/users/:user_id/roles/:role_id', to: 'UserRole#create', as: :new_user_role
		delete '/users/:user_id/roles/:role_id', to: 'UserRole#destroy', as: :destroy_user_role

        post '/areas/:area_id/users/:user_id/:relationship', to: 'AreasUsers#create', as: :new_area_user
		delete '/areas/:area_id/users/:user_id', to: 'AreasUsers#destroy', as: :destroy_area_user

		post '/areas/:area_id/regions/:region_id', to: 'AreasRegions#create', as: :new_area_region
		delete '/areas/:area_id/regions/:region_id', to: 'AreasRegions#destroy', as: :destroy_area_region
	end

    
    

	resources :households do 
		resources :interviews, shallow: true
		resources :people, shallow: true do
			resources :jobs, shallow: true
		end
        
	end

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  start      :datetime
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < SraModel
	json_attributes :id,
		:title,
		:start,
		:user_id,
		:created_at,
		:updated_at
	
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :authenticate_user!
	# GET /events
	# GET /events.json
	def index
		@events = current_user.events
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @events }
		end
	end

	# GET /events/1
	# GET /events/1.json
	def show
		@event = Event.find(params[:id])
		unless @event.user == current_user
			raise CanCan::AccessDenied
		end

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @event }
		end
	end

	# GET /events/new
	# GET /events/new.json
	def new
		@event = Event.new
		
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @event }
		end
	end

	# GET /events/1/edit
	def edit
		@event = Event.find(params[:id])
		
	end

	# POST /events
	# POST /events.json
	def create
		user = current_user
		
		@event = Event.new(params[:event]).create
		user.events << @event
		respond_to do |format|
			if response.status == 200
				format.html { redirect_to :dashboard}
				format.json { render json: @event, status: :created, location: @event }
			else
				format.html { render action: "new" }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /events/1
	# PUT /events/1.json
	def update
		@event = Event.find(params[:id])
		request = RestClient.post "https://sra-api.herokuapp.com/users/events/#{params[:id]}", {:event => params[:event]}

		respond_to do |format|
			if response.status == 200
				format.html { redirect_to @event, notice: 'Event was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /events/1
	# DELETE /events/1.json
	def destroy
		@event = Event.find(params[:id])
		@event.delete

		respond_to do |format|
			format.html { redirect_to events_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Start</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.start %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>Schedule Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Start:</b>
  <%= @event.start %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>