config/routes.rb
Sra::Application.routes.draw do

	get "search", to: "Search#search"
	
	post '/households', controller: :households, action: :index, as: :households
	
	root to: 'static#landing'
	
	get '/sessions/new', as: :new_user_session
	
	post '/sessions/create', controller: :sessions, action: :create, as: :login

	resources :events

	get "dashboard", to: "dashboard#show", as: :dashboard

	scope "/admin" do
		resources :users
		resources :roles
		resources :areas
		resources :regions

		post '/users/:user_id/roles/:role_id', to: 'UserRole#create', as: :new_user_role
		delete '/users/:user_id/roles/:role_id', to: 'UserRole#destroy', as: :destroy_user_role

        post '/areas/:area_id/users/:user_id/:relationship', to: 'AreasUsers#create', as: :new_area_user
		delete '/areas/:area_id/users/:user_id', to: 'AreasUsers#destroy', as: :destroy_area_user

		post '/areas/:area_id/regions/:region_id', to: 'AreasRegions#create', as: :new_area_region
		delete '/areas/:area_id/regions/:region_id', to: 'AreasRegions#destroy', as: :destroy_area_region
	end

    
    

	resources :households do 
		resources :interviews, shallow: true
		resources :people, shallow: true do
			resources :jobs, shallow: true
		end
        
	end

end

app/models/household.rb
# == Schema Information
#
# Table name: households
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Household < SraModel
	json_attributes :id,
	:name,
	:created_at
	:updated_at
	:user_id
    
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
	#before_filter :authenticate_user!

	# GET /households
	# GET /households.json
	def index
		@households = Household.all
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @households }
		end
	end

	# GET /households/1
	# GET /households/1.json
	def show
		@household = Household.find(params[:id])		
		@people = @household.people
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @household }
		end
	end

	# GET /households/new
	# GET /households/new.json
	def new
		@household = Household.new
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @household }
		end
	end

	# GET /households/1/edit
	def edit
		@household = Household.find(params[:id])
	
	end

	# POST /households
	# POST /households.json
	def create
		@household = Household.new(:household => params[:household]).create

		respond_to do |format|
			if response.status == 200
				format.html { redirect_to @household, notice: 'Household was successfully created.' }
				format.json { render json: @household, status: :created, location: @household }
			else
				format.html { render action: "new" }
				format.json { render json: @household.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /households/1
	# PUT /households/1.json
	def update
		@household = Household.find(params[:id])
		RestClient.post "http://sra-api.herokuapp.com/households/#{params[:id]}", {:household => params[:household]}
		@household = JSON.parse(request)
		respond_to do |format|
			if response.status
				format.html { redirect_to @household, notice: 'Household was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @household.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /households/1
	# DELETE /households/1.json
	def destroy
		@household = Household.find(params[:id])
		@household.delete		
		respond_to do |format|
			format.html { redirect_to households_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/MegaFormMegafrom.html.haml
= form_for(@household) do |f|
  .row
    = f.label :name, class: "col-sm-2"
    = f.text_field :name, class: [:textfield, "col-sm-8", "col-md-9"]

/dropdown menu
  .row
    = form.label :education_level, class: ["col-sm-4", "col-md-3"]
    = form.select :education_level, ['None', 'Some Elementary', 'Elementary', 'Some Secondary', 'Secondary', 'Some College', 'College']  

/checkbox  
  .row
    = form.label :in_school, class: ["col-sm-4", "col-md-3"]
    = form.check_box :in_school  

/prechecked checkbox  
  .row
    = form.label :is_alive, class: ["col-sm-4", "col-md-3"]
    = form.check_box :is_alive, checked: true 
  
  .row
    = f.submit 'Submit', class: [:btn, "btn-success", "btn-large", "col-sm-2"]

/Household questions----------------------------------------------------------
  .row
    = form.label :Who_owns_the_home, class: ["col-sm-4", "col-md-3"]
    = form.select :Who_owns_the_home, ['They Own', 'Leased', 'Borrowed', 'Gifted']

  .row
    = form.label :Roof, class: ["col-sm-4", "col-md-3"]
    = form.select :Roof, ['Cement', 'Tin', 'Tile', 'Thatch', 'Timber']

  .row
    = form.label :Wall, class: ["col-sm-4", "col-md-3"]
    = form.select :Wall, ['Brick', 'Adobe', 'Timber', 'Thatch']

  .row
    = form.label :Floor, class: ["col-sm-4", "col-md-3"]
    = form.select :Floor, ['Cement', 'Tile', 'Timber', 'Timber']

  .row
    = form.label :Number_of_sleeping_rooms, class: ["col-sm-4", "col-md-3"]
    = form.select :Number_of_sleeping_rooms, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']
  
  .row
    = form.label :kitchen_Separate, class: ["col-sm-4", "col-md-3"]
    = form.check_box :kitchen_Separate, checked: False 
 
  .row
    = form.label :Light, class: ["col-sm-4", "col-md-3"]
    = form.check_box :Light, checked: False 
 
  .row
    = form.label :Fule, class: ["col-sm-4", "col-md-3"]
    = form.select :Fule, ['Gas', 'wood', 'Combined', 'other']
  
  .row
    = form.label :Water_Sorce, class: ["col-sm-4", "col-md-3"]
    = form.select :Water_Sorce, ['Pipped', 'River or Canal', 'Well']

  .row
    = form.label :Water_is_Clorinated, class: ["col-sm-4", "col-md-3"]
    = form.check_box :Water_is_Clorinated, checked: False 
  
  .row
    = form.label :Bathroom, class: ["col-sm-4", "col-md-3"]
    = form.select :Bathroom, ['Outhouse', 'Open Field', 'Bathroom w/ Well']

  .row
    = form.label :Sewer_Disposal, class: ["col-sm-4", "col-md-3"]
    = form.select :Sewer_Disposal, ['Sewer', 'Open Field', 'Bogg']

/People In the home and their costs ----------------------------------------
  .row
    = form.label :Number_of_Peopel_in_Home, class: ["col-sm-4", "col-md-3"]
    = form.select :Number_of_Peopel_in_home, [@Numberofpeopelinhousehold]

  .row
    = form.label :Average_Income, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_Income [@Average_Income]

  .row
    = form.label :Average_cost_of_Shoes, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_cost_of_Shoes, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']

  .row
    = form.label :Average_cost_of_Medicin, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_cost_of_Medicin, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']

  .row
    = form.label :Average_cost_of_Normal_Schooling, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_cost_of_Normal_Schooling, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']
 
  .row
    = form.label :Average_cost_of_colledge, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_cost_of_colledge, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']
 
  .row
    = form.label :Average_cost_of_Water_and_Electrical, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_cost_of_Water_and_Electrical, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']
  
  .row
    = form.label :Average_cost_of_Misc, class: ["col-sm-4", "col-md-3"]
    = form.select :Average_cost_of_Misc, ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']

  .row
    = form.label :Radio, class: ["col-sm-4", "col-md-3"]
    = form.check_box :Radio, checked: false 
  
  .row
    = form.label :TV, class: ["col-sm-4", "col-md-3"]
    = form.check_box :TV, checked: false 
  
  .row
    = form.label :Referigerator, class: ["col-sm-4", "col-md-3"]
    = form.check_box :Referigerator, checked: false 

/Food!!!------------------------------------------------------------------
 /Staples 
   
   .row
    = form.label :Staples, class: ["col-sm-4", "col-md-3"]
    = form.select :Staples, ['Maize', 'Wheat', 'Rice', 'Noodles', 'Amaranth', 'Barly', 'Curry', 'Potato', 'Sweet Potato', 'Yam', 'Avena', 'Plantain', 'Cassava', 'Oats']  
    
    = form.label :amount, class: ["col-sm-4", "col-md-3"]
    = form.select :amount, ['Small', 'Normal', 'Large']
    
    = form.label :Often, class: ["col-sm-4", "col-md-3"]
    = form.select :Often, ['Daily', 'Weekly', 'Monthly']

/Protien
  .row
    = form.label :Protien, class: ["col-sm-4", "col-md-3"]
    = form.select :Protien, ['Beef', 'Pig', 'Chicken', 'Rabbit', 'Eggs', 'Lentel', 'Beans', 'Peanuts', 'Pea','Cuy']  
    
    = form.label :amount, class: ["col-sm-4", "col-md-3"]
    = form.select :amount, ['Small', 'Normal', 'Large']
    
    = form.label :Often, class: ["col-sm-4", "col-md-3"]
    = form.select :Often, ['Daily', 'Weekly', 'Monthly']

/Vegatables
  .row
    = form.label :Vegatables, class: ["col-sm-4", "col-md-3"]
    = form.select :Vegatables, ['Spinach', 'Turnip', 'Radish', 'Broccoli', 'Beet', 'Pumpkin', 'Radish Leaves', 'Col', 'Pickle', 'Squash', 'Gord', 'pope', 'Panela', 'carrot', 'Uvillas', 'Chard', 'Cauliflower', 'lettuce', 'Cabbage', 'Red Cabbage', 'Onion', 'Long onion', 'TomatoKidney']  
    
    = form.label :amount, class: ["col-sm-4", "col-md-3"]
    = form.select :amount, ['Small', 'Normal', 'Large']

    = form.label :Often, class: ["col-sm-4", "col-md-3"]
    = form.select :Often, ['Daily', 'Weekly', 'Monthly']

/Fruit
  .row
    = form.label :Fruit, class: ["col-sm-4", "col-md-3"]
    = form.select :Fruit, ['Tomato', 'Pepper', 'Lemmon', 'Tree Tomato', 'Strayberry', 'Bannana', 'Yucca']  
    
    = form.label :amount, class: ["col-sm-4", "col-md-3"]
    = form.select :amount, ['Small', 'Normal', 'Large']
    
    = form.label :Often, class: ["col-sm-4", "col-md-3"]
    = form.select :Often, ['Daily', 'Weekly', 'Monthly']

/fattening
  .row
    = form.label :Fattening, class: ["col-sm-4", "col-md-3"]
    = form.select :Fattening, ['Milk', 'Cheese', 'Butter', 'Oil', 'honey', 'Sugar'] 
    
    = form.label :amount, class: ["col-sm-4", "col-md-3"]
    = form.select :amount, ['Small', 'Normal', 'Large']
    
    = form.label :Often, class: ["col-sm-4", "col-md-3"]
    = form.select :Often, ['Daily', 'Weekly', 'Monthly']

/bought
  .row
    = form.label :Bought, class: ["col-sm-4", "col-md-3"]
    = form.select :Bought, ['Cooked Rice', 'Colada Oats Sweet', 'Soup wheat', 'Wheat Tortilla'] 
    
    = form.label :amount, class: ["col-sm-4", "col-md-3"]
    = form.select :amount, ['Small', 'Normal', 'Large']
    
    = form.label :Often, class: ["col-sm-4", "col-md-3"]
    = form.select :Often, ['Daily', 'Weekly', 'Monthly']

/People more info Needed ------------------------------------------------------
///job discription and pay  

/Personal cleaning habbits along with Food Preperation

/household do the people get sick
  .row
    = form.label :how_often_you_get_sick, class: ['col-sm-4', 'col-md-3']
    = form.select :how_often_you_get_sick, ['Monthly', 'biannual', 'Yearly', '4 years', '8 years']
  
  .row
    = form.label :treatments, class: ['col-sm-4', 'col-md-3']
    = form.select :treatments, ['in house', 'local shawman', 'Vet', 'Doctor']

app/views/households/_form.html.haml
= form_for(@household) do |f|
  .form-row
    = f.label :name
    .text-control
      = f.text_field :name, class: :'text-field'
  .row
    = f.submit 'Submit', class: [:'submit']

app/views/households/_household_list.html.haml
.row
	- @households.each do |household|
		.col-sm-6.col-md-4
			.panel.panel-primary
				.panel-heading
					%h3.panel-title
						= household.name
					= link_to 'X', household, method: :delete, id: "#{household.id}_remove"
				.panel-body.index
					- household.people.each do |person|
						%ul
							%li.alabel
								= "#{person.given_name} #{person.family_name}"
        
					= link_to 'Show', household, class: [:btn, "btn-success", "btn-lg", "col-md-5", "col-sm-5"], id: "#{household.id}_show"
					= link_to 'Edit', edit_household_path(household), class: [:btn, "btn-success", "btn-lg", "col-sm-5", "col-md-5", "col-md-offset-2", "col-sm-offset-2"], id: "#{household.id}_edit"

app/views/households/edit.html.haml
.row
  = link_to 'Back', households_path, class: [:btn, "btn-large", "btn-success", "col-sm-2", "col-md-2", :row], id: :back, method: :get
.row
  %h1
    = @household.name

.col-sm-12
  .panel.panel-pimary
    .panel-body
      = render 'form'

app/views/households/index.html.haml
%h1 
  Households
  
.row.btn-toolbar
  = link_to 'New Household', new_household_path, class: [:'toolbar-button'], id: :top

.row
  = render 'household_list'

app/views/households/new.html.haml
.container
  %h1
    New household
  .row
    .col-xs-12
      = render 'form'

app/views/households/show.html.haml
.container
  .row
    %h1
      = @household.name + " Household"

  - interviewed =  Interview.where({household_id: @household}).last

  .row
    .toolbar
      = link_to 'Add Person', new_household_person_path(@household), class: [:'toolbar-button'], id: "add_person_top"
      = link_to 'Rename', edit_household_path(@household), class: [:'toolbar-button'], id: "rename_top"
      - if interviewed
        = link_to 'Nutrition', interview_path(Interview.where({household_id: @household}).last), class: [:'toolbar-button'], id: "nutrition"
      - if @household.people.count > 0 and not interviewed
        = link_to 'Interview', new_household_interview_path(@household), class: [:'toolbar-button'], id: :interview_household

  - if @people.size > 0
    #people
      - @people.each do |person|
        .col-xs-12.col-sm-6.col-md-4
          .panel.panel-default
            .panel-heading
              %h3.panel-title
                %span.delete
                  = link_to 'x', person, method: :delete, id: "#{person.id}_remove"
                &nbsp;
                = "#{person.given_name} #{person.family_name}"
            .panel-body
              %ul
                %li.alabel
                  = person.gender
                %li.alabel 
                  = "Born #{person.birthday}"
              = link_to 'View', person_path(person), class: [:button, :'col-sm-5']
              = link_to 'Edit', edit_person_path(person), class: [:button, :'col-sm-5', :'col-sm-offset-2'], id: "#{person.id}_edit"
  - else
    .row
      %p.text-center.text-info
        Sorry, doesn't look like you've put any people in here yet.